apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-service
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: deploy/
    repoURL: git@github.com:adamstrawson/sa-service.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
